//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CategoriaProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriaProducto()
        {
            this.Productoes = new HashSet<Producto>();
        }
    
        [Display(Name = "Código")]
        public int idCatProd { get; set; }
        [Display(Name = "Nombre"), Required(ErrorMessage = "Este campo es obligatorio")]
        public string nombre { get; set; }
        [Display(Name = "Descripción"), Required(ErrorMessage = "Este campo es obligatorio")]
        public string descripcion { get; set; }
        [Display(Name = "Estado"), Required(ErrorMessage = "Este campo es obligatorio")]
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Productoes { get; set; }
    }
}
