//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ControlBono
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControlBono()
        {
            this.IngresoComunidadDets = new HashSet<IngresoComunidadDet>();
        }


        [Display(Name = "Bono")]
        public int idBono { get; set; }
        [Display(Name = "Bono")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(45, ErrorMessage = "El tamaño máximo es 45 caracteres")]
        public string nombre { get; set; }
        [Display(Name = "Valor")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [DataType(DataType.Currency, ErrorMessage = "Solo valores decimales")]
        public double valor { get; set; }
        public int estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngresoComunidadDet> IngresoComunidadDets { get; set; }
    }
}
