//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ControlBono
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControlBono()
        {
            this.IngresoComunidadDets = new HashSet<IngresoComunidadDet>();
        }
    
        public int idBono { get; set; }
        [Display(Name = "Bono")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(45, ErrorMessage = "El tamaño máximo es 45 caracteres")]

        public string nombre { get; set; }
        [Display(Name = "Valor")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [DataType(DataType.Currency)]
        [StringLength(53, ErrorMessage = "El tamaño máximo es 53 caracteres")]
        public double valor { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngresoComunidadDet> IngresoComunidadDets { get; set; }
    }
}
