//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Denominacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Denominacion()
        {
            this.ArqueoCajaDets = new HashSet<ArqueoCajaDet>();
        }
    
        public int idDenominacion { get; set; }
        [Display(Name = "Moneda")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int moneda { get; set; }
        [Display(Name = "Valor")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(18, ErrorMessage = "El tamaño máximo es 18 caracteres")]
        public decimal valor { get; set; }
        [Display(Name = "Valor en letras")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(100, ErrorMessage = "El tamaño máximo es 100 caracteres")]
        public string valorLetras { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArqueoCajaDet> ArqueoCajaDets { get; set; }
        public virtual Moneda Moneda1 { get; set; }
    }
}
