//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IngresoComunidadDet
    {
        [Display(Name = "Detalle de ingreso de comunidad")]
        public int idIngresoComunidadDet { get; set; }
        [Display(Name = "Ingreso de comunidad")]
        public int ingresoComunidad { get; set; }
        [Display(Name = "Bono")]
        public int bono { get; set; }
        [Display(Name = "Denominación")]
        [StringLength(45, ErrorMessage = "El tamaño máximo es 45 caracteres")]
        public string denominacion { get; set; }
        [Display(Name = "Cantidad")]
        public int cantidad { get; set; }
        [Display(Name = "Subtotal")]
        [DataType(DataType.Currency, ErrorMessage = "Solo valores decimales")]
        public double subTotalBono { get; set; }

        public virtual ControlBono ControlBono { get; set; }
        public virtual IngresoComunidad IngresoComunidad1 { get; set; }
    }
}