//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoComunidadDet
    {
        public int idIngresoComunidadDet { get; set; }
        public int ingresoComunidad { get; set; }
        public int bono { get; set; }
        public string denominacion { get; set; }
        public int cantidad { get; set; }
        public double subTotalBono { get; set; }
    
        public virtual ControlBono ControlBono { get; set; }
        public virtual IngresoComunidad IngresoComunidad1 { get; set; }
    }
}
