//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IngresoComunidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IngresoComunidad()
        {
            this.IngresoComunidadDets = new HashSet<IngresoComunidadDet>();
        }

        [Display(Name = "Ingreso de comunidad")]
        public int idIngresoComunidad { get; set; }

        [Display(Name = "Kermesse")]
        public Nullable<int> kermesse { get; set; }
        [Display(Name = "Comunidad")]
        public Nullable<int> comunidad { get; set; }
        [Display(Name = "Producto")]
        public Nullable<int> producto { get; set; }
        [Display(Name = "Cantidad producto")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int cantProducto { get; set; }
        [Display(Name = "Bonos totales")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int totalBonos { get; set; }
        [Display(Name = "Usuario creador")]
        public int usuarioCreacion { get; set; }
        [Display(Name = "Fecha de creación")]
        [DataType(DataType.DateTime)]
        public System.DateTime fechaCreacion { get; set; }
        [Display(Name = "Usuario modificación")]
        public Nullable<int> usuarioModificacion { get; set; }
        [Display(Name = "Fecha de modificación")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        [Display(Name = "Usuario eliminación")]
        public Nullable<int> usuarioEliminacion { get; set; }
        [Display(Name = "Fecha de eliminación")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> fechaEliminacion { get; set; }

        public virtual Comunidad Comunidad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngresoComunidadDet> IngresoComunidadDets { get; set; }
        public virtual Kermesse Kermesse1 { get; set; }
        public virtual Producto Producto1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
    }
}