//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ListaPrecio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListaPrecio()
        {
            this.ListaPrecioDets = new HashSet<ListaPrecioDet>();
        }

        [Display(Name = "Código")]
        public int idListaPrecio { get; set; }
        
        [Display(Name = "Kermesse")]
        public Nullable<int> kermesse { get; set; }
        [Display(Name = "Nombre"), Required(ErrorMessage = "Este campo es obligatorio")]
        public string nombre { get; set; }
        [Display(Name = "Descripción"), Required(ErrorMessage = "Este campo es obligatorio")]
        public string descripcion { get; set; }
        [Display(Name = "Estado"), Required(ErrorMessage = "Este campo es obligatorio")]
        public int estado { get; set; }
    
        public virtual Kermesse Kermesse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaPrecioDet> ListaPrecioDets { get; set; }
    }
}
