//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ListaPrecioDet
    {

        [Display(Name = "Detalle de lista de precio")]
        public int idListaPrecioDet { get; set; }
        [Display(Name = "Lista de precio")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int listaPrecio { get; set; }
        [Display(Name = "Producto")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int producto { get; set; }
        [Display(Name = "Precio venta")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [DataType(DataType.Currency, ErrorMessage = "Solo valores decimales")]
        public double precioVenta { get; set; }

        public virtual ListaPrecio ListaPrecio1 { get; set; }
        public virtual Producto Producto1 { get; set; }
    }
}