//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Moneda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Moneda()
        {
            this.ArqueoCajaDets = new HashSet<ArqueoCajaDet>();
            this.Denominacions = new HashSet<Denominacion>();
            this.TasaCambios = new HashSet<TasaCambio>();
            this.TasaCambios1 = new HashSet<TasaCambio>();
        }
        [Display(Name = "Moneda")]
        public int idMoneda { get; set; }
        [Display(Name = "Moneda")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(45, MinimumLength = 5, ErrorMessage = "M�ximo 45 caracteres, m�nimo 5")]
        [DataType(DataType.Text)]
        public string nombre { get; set; }
        [Display(Name = "Símbolo")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(45, ErrorMessage = "El tamaño máximo es 45 caracteres")]
        [DataType(DataType.Text)]
        public string simbolo { get; set; }

        public int estado { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArqueoCajaDet> ArqueoCajaDets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Denominacion> Denominacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasaCambio> TasaCambios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasaCambio> TasaCambios1 { get; set; }
    }
}