//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Moneda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Moneda()
        {
            this.ArqueoCajaDets = new HashSet<ArqueoCajaDet>();
            this.Denominacions = new HashSet<Denominacion>();
            this.TasaCambios = new HashSet<TasaCambio>();
            this.TasaCambios1 = new HashSet<TasaCambio>();
        }

        public int idMoneda { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 5, ErrorMessage = "Máximo 20 caracteres, mínimo 5")]
        [DataType(DataType.Text)]
        public string nombre { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string simbolo { get; set; }

        public int estado { get; set; }

        [Display(Name = "Prueba de display")]
        public string test { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArqueoCajaDet> ArqueoCajaDets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Denominacion> Denominacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasaCambio> TasaCambios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasaCambio> TasaCambios1 { get; set; }
    }
}
