//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Parroquia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parroquia()
        {
            this.Kermesses = new HashSet<Kermesse>();
        }

        public int idParroquia { get; set; }
        [Display(Name = "Parroquia")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string nombre { get; set; }
        [Display(Name = "Dirección")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string direccion { get; set; }
        [Display(Name = "Teléfono")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string telefono { get; set; }
        [Display(Name = "Párroco")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string parroco { get; set; }
        [Display(Name = "Logo")]
        public string logo { get; set; }
        [Display(Name = "Sitio Web")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string sitioWeb { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kermesse> Kermesses { get; set; }
    }
}
