//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rol()
        {
            this.RolOpcions = new HashSet<RolOpcion>();
            this.RolUsuarios = new HashSet<RolUsuario>();
        }
        [Display(Name = "Rol")]
        public int idRol { get; set; }
        [Display(Name = "Rol")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(70, ErrorMessage = "El tamaño máximo es 70 caracteres")]
        public string rolDescripcion { get; set; }
        public int estado { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolOpcion> RolOpcions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolUsuario> RolUsuarios { get; set; }
    }
}