//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RolOpcion
    {
        [Display(Name = "Rol Opción")]
        public int idRolOpcion { get; set; }
        [Display(Name = "Rol")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int rol { get; set; }
        [Display(Name = "Opci�n")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int opcion { get; set; }

        public virtual Opcion Opcion1 { get; set; }
        public virtual Rol Rol1 { get; set; }
    }
}