//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolUsuario
    {
        public int idRolUsuario { get; set; }
        public int usuario { get; set; }
        public int rol { get; set; }
    
        public virtual Rol Rol1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
