//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TasaCambioDet 
    {
        [Display(Name = "Código")]
        public int idTasaCambioDet { get; set; }
        [Display(Name = "Tasa de cambio")]
        public int tasaCambio { get; set; }
        [Display(Name = "Fecha")]
        public System.DateTime fecha { get; set; }
        [Display(Name = "Tipo de cambio")]
        public decimal tipoCambio { get; set; }
        [Display(Name = "Estado")]
        public int estado { get; set; }
        
        public virtual TasaCambio TasaCambio1 { get; set; }
    }
}
