//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic; using System.ComponentModel.DataAnnotations;
    
    public partial class VwArqueoCaja
    {
        public int idArqueoCaja { get; set; }
        public string kermesse { get; set; }
        public Nullable<System.DateTime> fechaArqueo { get; set; }
        public Nullable<decimal> granTotal { get; set; }
    }
}
