//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwArqueoCajaDet
    {
        public int idArqueoCajaDet { get; set; }
        public string moneda { get; set; }
        public string denominacion { get; set; }
        public decimal cantidad { get; set; }
        public decimal subtotal { get; set; }
    }
}
