//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic; using System.ComponentModel.DataAnnotations;
    
    public partial class VwDenominacione
    {
        public decimal Valor { get; set; }
        public string ValorLetras { get; set; }
        public string Moneda { get; set; }
        public int idDenominacion { get; set; }
    }
}
