//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwGasto
    {
        public int idGasto { get; set; }
        public string kermesse { get; set; }
        public string catGasto { get; set; }
        public System.DateTime fechGasto { get; set; }
        public string concepto { get; set; }
        public double monto { get; set; }
    }
}
