//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwGasto
    {
        public int idGasto { get; set; }
        public string kermesse { get; set; }
        public string catGasto { get; set; }
        public System.DateTime fechGasto { get; set; }
        public string concepto { get; set; }
        public double monto { get; set; }
    }
}
