//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic; using System.ComponentModel.DataAnnotations;
    
    public partial class VwIngresoComunidadDet
    {
        public int idIngresoComunidadDet { get; set; }
        public string bono { get; set; }
        public string denominacion { get; set; }
        public int cantidad { get; set; }
        public double subtotal { get; set; }
        public string comunidad { get; set; }
    }
}
