//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwIngresoComunidad
    {
        public int idIngresoComunidad { get; set; }
        public string kermesse { get; set; }
        public string comunidad { get; set; }
        public string producto { get; set; }
        public int cantProducto { get; set; }
        public int totalBonos { get; set; }
    }
}
