//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwKermesse
    {
        public int idKermesse { get; set; }
        public string Parroquia { get; set; }
        public string nombre { get; set; }
        public System.DateTime Fecha_de_inicio { get; set; }
        public System.DateTime Fecha_de_fin { get; set; }
        public string descripcion { get; set; }
        public string Usuario_creador { get; set; }
        public System.DateTime Fecha_de_creación { get; set; }
    }
}
