//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwListaPrecioDet
    {
        public int idListaPrecioDet { get; set; }
        public string producto { get; set; }
        public double precioVenta { get; set; }
        public int idListaPrecio { get; set; }
        public string listaprecio { get; set; }
    }
}
