//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwTasaCambio
    {
        public int idTasaCambio { get; set; }
        public string monedaO { get; set; }
        public string monedaC { get; set; }
        public string mes { get; set; }
        public int año { get; set; }
    }
}
